### ISSUE TITLE
Tìm hiểu về lập trình ứng dụng di động

### ISSUE THREAD

**Issue by Nvmanh472001** [Nvmanh472001/se2022-8.1#1]

**Comment by VietTran2707** [comment]
đã thấy công việc nhé

**Comment by VietTran2707** [comment]
push tài liệu vào file readme luôn à

**Comment by Nvmanh472001** [comment]
> push tài liệu vào file readme luôn à

Viết vào file readme rồi đưa vào trong folder theo tên issue để trong folder docs nha!

**Comment by daitran1412** [comment]
Đã thấy công việc nhé !!

**Comment by Pvtinh04** [comment]
Đã nhận
